// Auto-generated by optimize_gallery_photos.py
// Gallery images hosted on Google Cloud Storage

export interface GalleryImage {
  id: number;
  thumbnail: string;
  src: string;
  alt: string;
  width: number;
  height: number;
}

export const galleryImages: GalleryImage[] = [
  {
    id: 1,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DJI_20240913233511_0167_D-DNG.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DJI_20240913233511_0167_D-DNG.jpg',
    alt: 'SEVY gallery image: DJI_20240913233511_0167_D-DNG',
    width: 2400,
    height: 1349
  },
  {
    id: 2,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DJI_20240913234020_0171_D-DNG.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DJI_20240913234020_0171_D-DNG.jpg',
    alt: 'SEVY gallery image: DJI_20240913234020_0171_D-DNG',
    width: 2400,
    height: 1349
  },
  {
    id: 3,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06422.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06422.jpg',
    alt: 'SEVY gallery image: DUG06422',
    width: 2400,
    height: 1600
  },
  {
    id: 4,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06440.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06440.jpg',
    alt: 'SEVY gallery image: DUG06440',
    width: 2400,
    height: 1600
  },
  {
    id: 5,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06459.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06459.jpg',
    alt: 'SEVY gallery image: DUG06459',
    width: 2400,
    height: 1600
  },
  {
    id: 6,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06484.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06484.jpg',
    alt: 'SEVY gallery image: DUG06484',
    width: 2400,
    height: 1600
  },
  {
    id: 7,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06487.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06487.jpg',
    alt: 'SEVY gallery image: DUG06487',
    width: 2400,
    height: 1600
  },
  {
    id: 8,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06571.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06571.jpg',
    alt: 'SEVY gallery image: DUG06571',
    width: 2400,
    height: 1600
  },
  {
    id: 9,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06606.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06606.jpg',
    alt: 'SEVY gallery image: DUG06606',
    width: 2400,
    height: 1600
  },
  {
    id: 10,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06616.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06616.jpg',
    alt: 'SEVY gallery image: DUG06616',
    width: 2400,
    height: 1600
  },
  {
    id: 11,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06629.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06629.jpg',
    alt: 'SEVY gallery image: DUG06629',
    width: 2400,
    height: 1600
  },
  {
    id: 12,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06644.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06644.jpg',
    alt: 'SEVY gallery image: DUG06644',
    width: 2400,
    height: 1600
  },
  {
    id: 13,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/DUG06712.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/DUG06712.jpg',
    alt: 'SEVY gallery image: DUG06712',
    width: 2400,
    height: 1599
  },
  {
    id: 14,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_7040.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_7040.jpg',
    alt: 'SEVY gallery image: IMG_7040',
    width: 2400,
    height: 1612
  },
  {
    id: 15,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_7043.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_7043.jpg',
    alt: 'SEVY gallery image: IMG_7043',
    width: 2400,
    height: 1613
  },
  {
    id: 16,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_7044.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_7044.jpg',
    alt: 'SEVY gallery image: IMG_7044',
    width: 2400,
    height: 1613
  },
  {
    id: 17,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_8936.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_8936.jpg',
    alt: 'SEVY gallery image: IMG_8936',
    width: 2400,
    height: 1599
  },
  {
    id: 18,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_8951.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_8951.jpg',
    alt: 'SEVY gallery image: IMG_8951',
    width: 2400,
    height: 1600
  },
  {
    id: 19,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_8952.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_8952.jpg',
    alt: 'SEVY gallery image: IMG_8952',
    width: 2400,
    height: 1600
  },
  {
    id: 20,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_8955.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_8955.jpg',
    alt: 'SEVY gallery image: IMG_8955',
    width: 2400,
    height: 1600
  },
  {
    id: 21,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_8981.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_8981.jpg',
    alt: 'SEVY gallery image: IMG_8981',
    width: 2400,
    height: 1600
  },
  {
    id: 22,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_9101.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_9101.jpg',
    alt: 'SEVY gallery image: IMG_9101',
    width: 2400,
    height: 3600
  },
  {
    id: 23,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_9133.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_9133.jpg',
    alt: 'SEVY gallery image: IMG_9133',
    width: 2400,
    height: 1599
  },
  {
    id: 24,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_9135.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_9135.jpg',
    alt: 'SEVY gallery image: IMG_9135',
    width: 2400,
    height: 1600
  },
  {
    id: 25,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_9339.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_9339.jpg',
    alt: 'SEVY gallery image: IMG_9339',
    width: 2400,
    height: 1600
  },
  {
    id: 26,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_9349.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_9349.jpg',
    alt: 'SEVY gallery image: IMG_9349',
    width: 2400,
    height: 1600
  },
  {
    id: 27,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_9356.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_9356.jpg',
    alt: 'SEVY gallery image: IMG_9356',
    width: 2400,
    height: 1599
  },
  {
    id: 28,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_9367.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_9367.jpg',
    alt: 'SEVY gallery image: IMG_9367',
    width: 2400,
    height: 1599
  },
  {
    id: 29,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/IMG_9382.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/IMG_9382.jpg',
    alt: 'SEVY gallery image: IMG_9382',
    width: 2400,
    height: 1600
  },
  {
    id: 30,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-114.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-114.jpg',
    alt: 'SEVY gallery image: SEVY-114',
    width: 2400,
    height: 1599
  },
  {
    id: 31,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-127.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-127.jpg',
    alt: 'SEVY gallery image: SEVY-127',
    width: 2400,
    height: 3600
  },
  {
    id: 32,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-134.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-134.jpg',
    alt: 'SEVY gallery image: SEVY-134',
    width: 2400,
    height: 3600
  },
  {
    id: 33,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-135.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-135.jpg',
    alt: 'SEVY gallery image: SEVY-135',
    width: 2400,
    height: 1600
  },
  {
    id: 34,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-141.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-141.jpg',
    alt: 'SEVY gallery image: SEVY-141',
    width: 2400,
    height: 3600
  },
  {
    id: 35,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-208.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-208.jpg',
    alt: 'SEVY gallery image: SEVY-208',
    width: 2400,
    height: 3600
  },
  {
    id: 36,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-223.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-223.jpg',
    alt: 'SEVY gallery image: SEVY-223',
    width: 2400,
    height: 1599
  },
  {
    id: 37,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-81.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-81.jpg',
    alt: 'SEVY gallery image: SEVY-81',
    width: 2400,
    height: 1600
  },
  {
    id: 38,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-82.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-82.jpg',
    alt: 'SEVY gallery image: SEVY-82',
    width: 2400,
    height: 1600
  },
  {
    id: 39,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-93.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-93.jpg',
    alt: 'SEVY gallery image: SEVY-93',
    width: 2400,
    height: 3600
  },
  {
    id: 40,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-94.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-94.jpg',
    alt: 'SEVY gallery image: SEVY-94',
    width: 2400,
    height: 1600
  },
  {
    id: 41,
    thumbnail: 'https://storage.googleapis.com/sevyai-images/gallery/thumbnails/SEVY-98.jpg',
    src: 'https://storage.googleapis.com/sevyai-images/gallery/full/SEVY-98.jpg',
    alt: 'SEVY gallery image: SEVY-98',
    width: 2400,
    height: 3600
  },
];
